### PR TITLE
Add DecodeDraw to allow custom image types

### LINKED ISSUE #2: Add DecodeDraw to allow custom image types
Originally, the library only has a `Decode` function that would always return an `*image.NRGBA`. This is a minor inconvenience, as some other functions (such as `libjpeg`'s) can only do `RGBA` or other image types.

As a fix for the above inconvenience, a `DecodeDraw` function was added:

```go
func DecodeDraw(dst draw.Image, hash string, punch float64) error
```

This function decodes the given hash and punch (which is now float64 for granularity) and draws the decoded image onto the given `draw.Image`.

The older `Decode` function now calls `DecodeDraw` internally on an `*image.NRGBA`. This ensures that the API isn't broken.

#### Benchmarks

After the changes, with `Decode` now calling `DecodeDraw`:

```
goos: linux
goarch: amd64
pkg: github.com/bbrks/go-blurhash
BenchmarkComponents/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8         	62727241	        18.2 ns/op
BenchmarkComponents/LNAdApj[00aymkj[TKay9}ay-Sj[-8         	66509407	        17.9 ns/op
BenchmarkComponents/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8         	56069827	        18.0 ns/op
BenchmarkComponents/KJG8_@Dgx]_4V?xuyE%NRj-8               	67373836	        17.9 ns/op
BenchmarkDecode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8             	    1254	    924818 ns/op
BenchmarkDecode/LNAdApj[00aymkj[TKay9}ay-Sj[-8             	    1296	    882316 ns/op
BenchmarkDecode/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8             	    1214	    940441 ns/op
BenchmarkDecode/KJG8_@Dgx]_4V?xuyE%NRj-8                   	    1431	    805385 ns/op
BenchmarkEncode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8             	       6	 187144765 ns/op
BenchmarkEncode/LNAdApj[00aymkj[TKay9}ay-Sj[-8             	       9	 122129504 ns/op
PASS
ok  	github.com/bbrks/go-blurhash	16.277s
```

Before the changes:

```
goos: linux
goarch: amd64
pkg: github.com/bbrks/go-blurhash
BenchmarkComponents/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8         	67750879	        18.4 ns/op
BenchmarkComponents/LNAdApj[00aymkj[TKay9}ay-Sj[-8         	56951818	        23.9 ns/op
BenchmarkComponents/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8         	41726830	        26.1 ns/op
BenchmarkComponents/KJG8_@Dgx]_4V?xuyE%NRj-8               	50471245	        26.8 ns/op
BenchmarkDecode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8             	     962	   1295024 ns/op
BenchmarkDecode/LNAdApj[00aymkj[TKay9}ay-Sj[-8             	    1233	    976301 ns/op
BenchmarkDecode/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8             	    1249	   1128537 ns/op
BenchmarkDecode/KJG8_@Dgx]_4V?xuyE%NRj-8                   	    1171	   1109666 ns/op
BenchmarkEncode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8             	       6	 190812766 ns/op
BenchmarkEncode/LNAdApj[00aymkj[TKay9}ay-Sj[-8             	       9	 120429582 ns/op
PASS
ok  	github.com/bbrks/go-blurhash	16.912s
```

Note: the performance is roughly the same, as the compiler is probably smart enough to know and inline the function call.

### PR DESCRIPTION
**Pull request by diamondburned**
Closes #2

### CODE REVIEW

**Comment by bbrks** [comment]
Hey, thanks for the contribution!

The detailed writeup in the issue makes sense to me, as well as the cursory glance over the PR.
I'll have a play around with this a little bit in my day tomorrow and merge if all looks good 👍

**Comment by bbrks** [comment]
Sorry, this is taking a little longer than expected. I ran into an issue when testing this where the new interface-based `image.Set` is causing a huge increase in allocations for the default Decode method (for NRGBA images).

I can work around it by doing a type check to switch to the faster paths for known image types, but want to be sure I've not screwed anything up in the process of switching between alpha and non-alpha premultiplied colors when doing so.

```golang
16:50 $ benchcmp bench-master.txt bench-new.txt
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark                                          old ns/op     new ns/op     delta
BenchmarkDecode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8     820101        815481        -0.56%
BenchmarkDecode/LNAdApj[00aymkj[TKay9}ay-Sj[-8     750371        761578        +1.49%
BenchmarkDecode/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8     816556        823240        +0.82%
BenchmarkDecode/KJG8_@Dgx]_4V?xuyE%NRj-8           687708        699058        +1.65%

benchmark                                          old allocs     new allocs     delta
BenchmarkDecode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8     3              1027           +34133.33%
BenchmarkDecode/LNAdApj[00aymkj[TKay9}ay-Sj[-8     3              1027           +34133.33%
BenchmarkDecode/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8     3              1027           +34133.33%
BenchmarkDecode/KJG8_@Dgx]_4V?xuyE%NRj-8           3              1027           +34133.33%

benchmark                                          old bytes     new bytes     delta
BenchmarkDecode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8     4448          8544          +92.09%
BenchmarkDecode/LNAdApj[00aymkj[TKay9}ay-Sj[-8     4448          8544          +92.09%
BenchmarkDecode/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8     4448          8544          +92.09%
BenchmarkDecode/KJG8_@Dgx]_4V?xuyE%NRj-8           4384          8480          +93.43%
```

**Comment by diamondburned** [comment]
That's an interesting observation. I'm guessing it has to do with the type assertion [here](https://golang.org/src/image/color/color.go#L193), which possibly creates a copy of `color.NRGBA`.

I think a fast path approach is reasonable. Something like this, I assume:

```go
setter, isNRGBA := dst.(*image.NRGBA)

for .. {
    for .. {
        if isNRGBA {
            setter.SetNRGBA(x, y, color.NRGBA{})
        } else {
            dst.Set(x, y, color.NRGBA{})
        }
    }
}
```

Edit: It seems like inlining `color.NRGBA` doesn't have any benefits compiler-wise. Below are 2 Godbolt links that possibly demonstrate this:

- Inlined struct: https://godbolt.org/z/5djqeE
- Variable-constructed struct: https://godbolt.org/z/z6fGas

As we can see, the Go code and Assembly outputs for both pastes are different. However, what's more important is that both have the same amount of `movq` instructions, thus in either cases, they will treat the struct values the same.

Given this, I can rewrite the above example as such:

```go
for .. {
    for .. {
        var c = color.NRGBA{}

        if isNRGBA {
            setter.SetNRGBA(x, y, c)
        } else {
            dst.Set(x, y, c)
        }
    }
}
```

**Comment by bbrks** [comment]
I think this is going to end up being just as alloc heavy when using an RGBA image instead of an NRGBA image. I've played around a little and got a fast path low-alloc approach for both cases. Only downside that I can see is the type switch is inside the loop, but the benchmark doesn't show any impact.

What do you think?

```golang
type drawImageNRGBA interface {
	SetNRGBA(x, y int, c color.NRGBA)
}

type drawImageRGBA interface {
	SetRGBA(x, y int, c color.RGBA)
}
```

```golang
for .. {
    for .. {

			switch d := dst.(type) {
			case *image.NRGBA:
				d.SetNRGBA(x, y, color.NRGBA{
					R: uint8(linearTosRGB(r)),
					G: uint8(linearTosRGB(g)),
					B: uint8(linearTosRGB(b)),
					A: 255,
				})
			case *image.RGBA:
				d.SetRGBA(x, y, color.RGBA{
					R: uint8(linearTosRGB(r)),
					G: uint8(linearTosRGB(g)),
					B: uint8(linearTosRGB(b)),
					A: 255,
				})
			default:
				d.Set(x, y, color.NRGBA{
					R: uint8(linearTosRGB(r)),
					G: uint8(linearTosRGB(g)),
					B: uint8(linearTosRGB(b)),
					A: 255,
				})
			}

```

```
22:01 $ benchstat orig.txt pr.txt pr-switch2.txt
name \ time/op                             orig.txt     pr.txt        pr-switch2.txt
Decode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8       874µs ± 7%    825µs ± 1%      795µs ± 1%
Decode/LNAdApj[00aymkj[TKay9}ay-Sj[-8       801µs ± 3%    765µs ± 1%      733µs ± 1%
Decode/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8       881µs ±10%    831µs ± 0%      798µs ± 1%
Decode/KJG8_@Dgx]_4V?xuyE%NRj-8             756µs ±11%    702µs ± 1%      669µs ± 1%
DecodeDraw/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8                 851µs ± 1%      813µs ± 3%
DecodeDraw/LNAdApj[00aymkj[TKay9}ay-Sj[-8                 787µs ± 0%      742µs ± 3%
DecodeDraw/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8                 852µs ± 0%      797µs ± 1%
DecodeDraw/KJG8_@Dgx]_4V?xuyE%NRj-8                       726µs ± 1%      668µs ± 0%

name \ alloc/op                            orig.txt     pr.txt        pr-switch2.txt
Decode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8      4.45kB ± 0%   8.54kB ± 0%     4.45kB ± 0%
Decode/LNAdApj[00aymkj[TKay9}ay-Sj[-8      4.45kB ± 0%   8.54kB ± 0%     4.45kB ± 0%
Decode/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8      4.45kB ± 0%   8.54kB ± 0%     4.45kB ± 0%
Decode/KJG8_@Dgx]_4V?xuyE%NRj-8            4.38kB ± 0%   8.48kB ± 0%     4.38kB ± 0%
DecodeDraw/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8                8.48kB ± 0%     0.29kB ± 0%
DecodeDraw/LNAdApj[00aymkj[TKay9}ay-Sj[-8                8.48kB ± 0%     0.29kB ± 0%
DecodeDraw/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8                8.48kB ± 0%     0.29kB ± 0%
DecodeDraw/KJG8_@Dgx]_4V?xuyE%NRj-8                      8.42kB ± 0%     0.23kB ± 0%

name \ allocs/op                           orig.txt     pr.txt        pr-switch2.txt
Decode/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8        3.00 ± 0%  1027.00 ± 0%       3.00 ± 0%
Decode/LNAdApj[00aymkj[TKay9}ay-Sj[-8        3.00 ± 0%  1027.00 ± 0%       3.00 ± 0%
Decode/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8        3.00 ± 0%  1027.00 ± 0%       3.00 ± 0%
Decode/KJG8_@Dgx]_4V?xuyE%NRj-8              3.00 ± 0%  1027.00 ± 0%       3.00 ± 0%
DecodeDraw/LFE.@D9F01_2%L%MIVD*9Goe-;WB-8                 2.05k ± 0%      0.00k ± 0%
DecodeDraw/LNAdApj[00aymkj[TKay9}ay-Sj[-8                 2.05k ± 0%      0.00k ± 0%
DecodeDraw/LNMF%n00%#MwS|WCWEM{R*bbWBbH-8                 2.05k ± 0%      0.00k ± 0%
DecodeDraw/KJG8_@Dgx]_4V?xuyE%NRj-8                       2.05k ± 0%      0.00k ± 0%
```

```golang
func BenchmarkDecodeDraw(b *testing.B) {
	for _, test := range testFixtures {
		// skip tests without hashes
		if test.hash == "" {
			continue
		}

		b.Run(test.hash, func(b *testing.B) {
			dst := image.NewRGBA(image.Rect(0, 0, 32, 32))
			for i := 0; i < b.N; i++ {
				_ = blurhash.DecodeDraw(dst, test.hash, 1)
			}
		})
	}
}
```

**Comment by diamondburned** [comment]
I think the color should be created outside the type switch to make it shorter. Other than that, I think it's fine.

**Comment by bbrks** [comment]
Sorry this took a while to merge! I've been tied up with work stuff recently.

**Pull request merged**
